services:
  - type: web
    name: nihal-flask-server
    env: python
    buildCommand: ""
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    plan: free
    envVars:
      - key: PORT
        value: "10000"
